import gestor_reservas
import time

print("--- INICIO EJERCICIO 1 ---")
time.sleep(1)
print("1.- Se va a crear el fichero de reservas.")
time.sleep(1)
gestor_reservas.crear_archivo_reservas()
print("- Se ha creado el fichero reservas.txt")
time.sleep(1)
print("2.- Se van a escribir las reservas en el fichero.")
time.sleep(1)
gestor_reservas.escribir_archivo_reservas()
print("- Se han escrito las reservas en el fichero reservas.txt")
time.sleep(1)
print("3.- Se van a leer las reservas del fichero.")
time.sleep(1)
gestor_reservas.leer_reservas()
time.sleep(1)
print("4.- Se van a contar las reservas del fichero.")
time.sleep(1)
print(gestor_reservas.contar_reservas())
time.sleep(1)
print("5.- Se van a filtrar las reservas por la clase 'Business'.")
time.sleep(1)
gestor_reservas.filtrar_reservas_por_clase("Business")
time.sleep(1)
print("--- FIN EJERCICIO 1 ---")